sudo: false

branches:
    only:
        - develop
        - master

language: groovy

jdk: oraclejdk8

script:
    - ./gradlew application:build
    - ./gradlew base:build
    - ./gradlew jacoco:build
    - ./gradlew library:build
    - ./gradlew robolectric:build
    - ./gradlew lint:build

after_success:
    - ./travis_deploy.sh
