coverage:
  status:
    project:
      default: off
      # Minimum coverage that our project must have
      minimum:
        target: 50%
      # Decrement threshold for code coverage when submitting a PR
      decrement:
        target: auto
        threshold: 0.5%
        if_not_found: success
